Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 10
Rules claiming more threads will be scaled down.
Job stats:
job                          count
-------------------------  -------
all                              1
delete_filtered_annot_vcf        1
get_plot_files_rule              1
make_SNP_plot                    1
total                            4

Resources before job selection: {'_cores': 10, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 9, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Fri Sep  6 16:06:43 2024]
localrule get_plot_files_rule:
    input: /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/HG00151-ONT-hg38-R9-LSK110-guppy-sup-5mC.annotated.filtered.bed, /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/HG01046-ONT-hg38-R9-LSK110-guppy-sup-5mC.annotated.filtered.bed, /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/HG01695-ONT-hg38-R9-LSK110-guppy-sup-5mC.annotated.filtered.bed
    output: /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/file_list.txt
    jobid: 2
    reason: Set of input files has changed since last execution
    resources: tmpdir=/tmp

Activating conda environment: iPython-8.15.0
Completion of job ['get_plot_files_rule'] reported to scheduler.
jobs registered as running before removal {get_plot_files_rule}
[Fri Sep  6 16:06:44 2024]
Finished job 2.
1 of 4 steps (25%) done
Resources before job selection: {'_cores': 10, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 9, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Fri Sep  6 16:06:44 2024]
localrule make_SNP_plot:
    input: /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/file_list.txt
    output: SNP-Plots/NMU2-SNP-PLOT.svg
    jobid: 1
    reason: Missing output files: SNP-Plots/NMU2-SNP-PLOT.svg; Input files updated by another job: /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/file_list.txt
    resources: tmpdir=/tmp

Activating conda environment: Rtools-1.1
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake-testing/workflow/rules/make-SNP-plot.smk", line 27, in __rule_make_SNP_plot
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1563, in script
    executor.evaluate()
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 454, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 833, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 482, in _execute_cmd
    return shell(
           ^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake-testing/.snakemake/scripts/tmptnbib5oa.SNP-plot.R' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake-testing/workflow/rules/make-SNP-plot.smk", line 27, in __rule_make_SNP_plot
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1563, in script
    executor.evaluate()
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 454, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 833, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 482, in _execute_cmd
    return shell(
           ^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake-testing/.snakemake/scripts/tmptnbib5oa.SNP-plot.R' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /n/zanderson/SNP-plot-snake-testing/workflow/rules/make-SNP-plot.smk, line 11:
Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake-testing/.snakemake/scripts/tmptnbib5oa.SNP-plot.R' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /n/zanderson/SNP-plot-snake-testing/workflow/rules/make-SNP-plot.smk, line 11:
Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake-testing/.snakemake/scripts/tmptnbib5oa.SNP-plot.R' returned non-zero exit status 1.
[Fri Sep  6 16:06:46 2024]
Error in rule make_SNP_plot:
    jobid: 1
    input: /n/zanderson/SNP-plot-snake-testing/filtered-annotated-VCFs/file_list.txt
    output: SNP-Plots/NMU2-SNP-PLOT.svg
    conda-env: Rtools-1.1

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-06T160642.219632.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
