Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 128
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
make_SNP_plot        1
total                2

Resources before job selection: {'_cores': 128, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 127, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Mon Aug 26 17:09:16 2024]
localrule make_SNP_plot:
    input: /n/zanderson/SNP-plot-snake/filtered-annotated-VCFs/file_list.txt, /n/zanderson/SNP-plot-snake/1000G_Sample_Demographic_Info.txt
    output: /n/zanderson/SNP-plot-snake/SNP-Plots/SNP-plot-20240826.svg
    jobid: 1
    reason: Missing output files: /n/zanderson/SNP-plot-snake/SNP-Plots/SNP-plot-20240826.svg
    resources: tmpdir=/tmp

Activating conda environment: Rtools-1.1
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/make-SNP-plot.smk", line 23, in __rule_make_SNP_plot
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1563, in script
    executor.evaluate()
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 454, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 833, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 482, in _execute_cmd
    return shell(
           ^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake/.snakemake/scripts/tmpdfyyrgav.SNP-plot.R' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/n/zanderson/SNP-plot-snake/workflow/rules/make-SNP-plot.smk", line 23, in __rule_make_SNP_plot
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 1563, in script
    executor.evaluate()
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 454, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 833, in execute_script
    self._execute_cmd("Rscript --vanilla {fname:q}", fname=fname)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/script/__init__.py", line 482, in _execute_cmd
    return shell(
           ^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake/.snakemake/scripts/tmpdfyyrgav.SNP-plot.R' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/make-SNP-plot.smk, line 10:
Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake/.snakemake/scripts/tmpdfyyrgav.SNP-plot.R' returned non-zero exit status 1.

RuleException:
CalledProcessError in file /n/zanderson/SNP-plot-snake/workflow/rules/make-SNP-plot.smk, line 10:
Command 'source /usr/bin/activate 'Rtools-1.1'; set -euo pipefail;  Rscript --vanilla /n/zanderson/SNP-plot-snake/.snakemake/scripts/tmpdfyyrgav.SNP-plot.R' returned non-zero exit status 1.
[Mon Aug 26 17:09:19 2024]
Error in rule make_SNP_plot:
    jobid: 1
    input: /n/zanderson/SNP-plot-snake/filtered-annotated-VCFs/file_list.txt, /n/zanderson/SNP-plot-snake/1000G_Sample_Demographic_Info.txt
    output: /n/zanderson/SNP-plot-snake/SNP-Plots/SNP-plot-20240826.svg
    conda-env: Rtools-1.1

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-26T170912.486223.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/usr/share/millerlab/snakemake-8.16.0/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
